#!/bin/ksh -ph

#Figure out location of BASEDIR
BASEDIR=${0%/bin/*}
BASEDIR=${BASEDIR:-/usr} 

PATH=/usr/bin:/usr/sbin:/sbin:${BASEDIR}/sbin:${PATH}
export PATH

NWAM_MANAGER_PROPERTIES=${BASEDIR}/lib/nwam-manager-properties
GKSU=/usr/bin/gksu
AUTHS=$(auths)

if echo $AUTHS | egrep -s '(^\*|solaris\.\*|solaris\.network\.\*|solaris\.network\.autoconf\.\*)'; then
	HAS_AUTHS="yyyy"
else
    HAS_AUTHS=""
    if echo $AUTHS | egrep -s 'solaris\.network\.autoconf\.read'; then
	HAS_AUTHS="${HAS_AUTHS}y"
    fi
    if echo $AUTHS | egrep -s 'solaris\.network\.autoconf\.wlan'; then
	HAS_AUTHS="${HAS_AUTHS}y"
    fi
    if echo $AUTHS | egrep -s 'solaris\.network\.autoconf\.select'; then
	HAS_AUTHS="${HAS_AUTHS}y"
    fi
    if echo $AUTHS | egrep -s 'solaris\.network\.autoconf\.write'; then
	HAS_AUTHS="${HAS_AUTHS}y"
    fi
fi

isRunningNWAM() {
    state_nwam=`/usr/bin/svcs -H -o state svc:/network/physical:nwam 2>/dev/null`

    if [ "${state_nwam}" = "online" ]
    then
        return 0
    else
        return 1
    fi
}


if isRunningNWAM; then
    if [ x"$HAS_AUTHS" = xyyyy ]; then
	exec $NWAM_MANAGER_PROPERTIES "$@"
    else
	exec $GKSU "$NWAM_MANAGER_PROPERTIES $@"
    fi
else
    exec ${BASEDIR}/bin/network-admin ${1+"$@"}
fi
